### PR TITLE
Fixed deserialization with TypeSerializers, BLOB/byte[] support, and DataSetObserver

### PR DESCRIPTION
**Pull request by zach-klippenstein**
This is my first pull request to a public project, so I apologize in advance if I haven't followed the expected etiquette. I think 4 commits might be a bit much for one request, but I hope at least some of this is up to the standards of the project.

65a5ddd is just a format cleanup I noticed while working on the other stuff. The other 3 are more major:
1. fd8a5d4 I was implementing a custom Adapter sourced from a From object, and since CursorAdapters get notified by Cursors when backing data changes, I thought it would be nice to have similar functionality here. This implementation isn't ideal, since changes are only monitored at the table level, but tracking the list of results for each query would require a lot more complexity -- this is fairly simple.
2. 8a747a2 Fixes issue #8. The commit description explains the fix. If existing serializers _were_ working, I'm not sure how. I'm very open to any suggestions on how to fix this in a better way. In particular, I couldn't figure out how to fix it without having TypeSerializers provide the java class of their serialized type, since the class-to-SQLiteType mapping isn't one-to-one (e.g. if SQLiteType is REAL, call getFloat() or getDouble()?). In addition to breaking existing code, another problem with this fix is that there is no compile-time checking that the serialized type is valid. The best alternative I could think of is checking TYPE_MAP.containsValue(typeSerializer.getSerializedType()) when registering TypeSerializers on initialization.
3. 7b2e0c5 Byte arrays are trivially serialized using the SQLite BLOB type, so I added the trivial code for that.

Let me know what you think, I would be happy to implement any suggestions.

### CODE REVIEW

**Comment by marcel-rf** [comment]
I began testing the library some days ago, and found out about the broken TypeSerializer. 
I wrote a few of these to serialize enums and running any query on them returned empty. 
Your fixes fixed my setup with minor changes.

**Comment by zach-klippenstein** [comment]
Could you post the changes?

**Comment by marcel-rf** [comment]
For minor changes I meant the changes to my custom TypeSerializers. The code is just fine as it is. At least I haven't run into any issues so far.

**Comment by dbalaouras** [comment]
I cherry-picked commit 8a747a2 and I can verify it fixed issue #8 .

**Comment by pardom-zz** [comment]
I cherry-picked 8a747a2 and 7b2e0c5. You appear to have already seen why I won't merge fd8a5d4, and good catch on the formatting in 65a5ddd, but SQLiteUtils.processCursor() is meant to be public, so instead of merging that I left it as is, but removed the comment header.

Thanks!

**Comment by zach-klippenstein** [comment]
Is change notification something that you would like to eventually see added? Some other ideas for implementations that would associate notifications with specific queries (i.e. Froms):
1. **SQL triggers:** Each From stores its own set of observers. When a From is observed, it adds insert/update/delete triggers predicated on the query that logs the change to a journal table along with a From identifier (its hashCode(), or an ID generated by the DB then saved in a field in the From). Then after each save/delete, the journal table is checked for related entries, and sends notifications if necessary. The From drops its trigger when the last observer stops observing.
   - Pro: Would involve implementing support for triggers, which could be exposed to users
   - Pro: The work of tracking changes related to a specific query is delegated to the DB engine
   - Con: Some extra I/O overhead for all Model operations (checking the journal table)
   - Con: Would require "reserving" a table name for the journal
2. **In-memory:** Each From stores its own set of observers and set of result IDs, and a mapping of tables to Froms is maintained. Every time a Model is saved/deleted, the Froms that are associated with that table and include that model's ID send change notifications. Inserts would require running all the table's From queries to determine which include the new model.
   - Pro: No extra database code, and no storage space required for a journal table
   - Pro/Con: Database overhead only for insert operations, but each insert requires _every_ From query associated with the table to be executed
   - Con: More memory overhead for storing ID sets

Since both of these represent a pairing of query with results, it might make more sense to use a custom results list class that can be observed instead, and is aware of it's source query. Either way, Froms or results would need to be "closed," like Cursors.

**Comment by SeanPONeil** [comment]
Are Observers still on the roadmap? If not, what's the reasoning behind not including them?

**Comment by zach-klippenstein** [comment]
Even if they're not, just making the Model save()/delete() instance methods non-final would be helpful, so one could use implement custom behaviours on those events. I.e. Issue #28.

**Pull request closed without merging**
