### PR TITLE
Add AA_DB_RESET flag

### PR DESCRIPTION
**Pull request by jlhonora**
There are certain SQLite features that are hard to
set or modify in an existing DB, such as:
- Set foreign key actions
- Rename columns or tables
- `ON (UPDATE|CREATE)` definitions

They usually require creating a new table, dropping
the old one, and renaming the new one. If a full
db reset is performed then these definitions can be
included without migration scripts.

Reset capabilities are added with these changes. A
db delete/create will be issued whenever the
`AA_DB_VERSION` changes and the following lines
exist in the app's manifest:

```
<meta-data
    android:name="AA_DB_RESET"
    android:value="true" />
```

The reset will be checked in the `Cache.initialize`
method.

ps: This change also includes the changes for the Travis CI
 setup (PR https://github.com/pardom/ActiveAndroid/pull/310).
I'm not sure which approach is worse:
1. Open a PR with a failed Travis build.
2. Open a PR with changes from another PR.

Please let me know if you prefer approach number 1.

### CODE REVIEW

**Comment by sriram-kakarala** [comment]
Thank you for the reference. But I think this would cause the entire data to be reset, is that correct?
I was planning to handle exceptions on a case by case basis during upgrade.

**Comment by jlhonora** [comment]
Unfortunately yes, the data will be wiped.

**Comment by oleonov** [comment]
When will AA_DB_RESET be available?

**Comment by oleonov** [comment]
Who can merge changes into master branch? I need this feature.

**Comment by jlhonora** [comment]
@oleonov Actually I was thinking about closing this PR, since the same functionality can be easily achieved by just changing the database name (with the AA_DB_NAME tag). Sometimes this is not possible or desired, but for me it works just as well as putting an AA_DB_RESET flag.

Renaming the database is actually even better: If you use AA_DB_RESET you are stuck with it in all further migrations, but with renaming you have a clean slate in your app's DB. Why? Look at this case:

DB version 1: First Schema
DB version 2: AA_DB_RESET = true, Second Schema.
DB version 3: AA_DB_RESET = false, Additional migration script, third schema.

If a user jumps from version 1 to 3 the database won't be reset, and the app will most likely crash.

It does have a small drawback: the old database won't be deleted in the new install. If your DB is big then you'll be wasting valuable space, but this could be checked in the app's initialization.

**Comment by oleonov** [comment]
@jlhonora thank you, I will change the name.

**Pull request closed without merging**
