### PR TITLE
Save and delete callbacks + Testcases

### PR DESCRIPTION
**Pull request by vonloxley**
Allow subclasses of Model to be notified before save and delete
operations take place and optionally raise an exception if the framework
shouldn’t continue with the operation.

### CODE REVIEW

**Comment by zach-klippenstein** [comment]
Is there any advantage to adding callback methods instead of just making save/delete non-final?

**Comment by vonloxley** [comment]
From my point of view? Perhaps. Making them overwritable means that users can modify their behavior in unforeseeable ways. Implementing a direct callback gives the users the benefits of being able to interfere with the save-process in a safe manner. The can do whatever they want, even cancel the save-process, but they can’t meddle with the actual save.

**Comment by zach-klippenstein** [comment]
The only meddling one could do with overrides is cancelling the operation by not calling super.save(). Overriding save directly is more flexible: it allows subclasses to run code before _and_/or after the actual save.

**Comment by vonloxley** [comment]
If people were able to override save() they would be responsible for the whole save-operation and might implement it in a very different way. I prefer a solution where the framework always knows which save() it calls. But let’s agree to disagree. I see the merits of using a non-final save(), but like the more conservative approach where users are able to prevent a central function from happening, but are forced to do so by raising an exception.

**Pull request closed without merging**
