### PR TITLE
Add method in Table annotation to set column Id name.

### PR DESCRIPTION
**Pull request by hube**
I merged #132 with the latest master. I couldn't figure out how to submit these changes to that PR, so I created this one instead.

### CODE REVIEW

**Comment by joshuapinter** [comment]
@SeanPONeil Can we get this pull request merged in, seems like a key feature to be able to set the `Id` column. What's nice is that it defaults to the regular "Id" unless you specifically set it, so it shouldn't cause any conflict.

**Comment by SeanPONeil** [comment]
I should have waited for the Travis build to pass before merging :/. Any idea why this is failing?

**Comment by joshuapinter** [comment]
I'll take a look.

**Comment by joshuapinter** [comment]
I created another pull request to fix the issue raised with this pull request (is there a better way to do this?). If you merge that PR in the tests run swimmingly once again.

On a further note, it'd be great to require tests for this new functionality. The issue was due to the Index Groups and Unique Groups not being able to handle the custom Id column naming. I was able to work around it but without tests for those pieces I can't be certain they weren't affected.

**Comment by hube** [comment]
Thanks for merging! Sorry about the broken build, I didn't run the tests after I merged in the old PR :(

**Pull request merged**
